<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\Bestsaller
 */
?>
<?php
//  $image = 'new_products_content_widget_grid';
// $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
// $productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
// $category = $objectManager->create('Magento\Catalog\Model\Category')->load('84');
// $collection = $productCollection->create()
//         ->addAttributeToSelect('*')
//         ->addCategoryFilter($category)
//         ->load();
?>
