<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
//$_settingHelper = $this->helper('Emthemes\ThemeSettings\Helper\Data'); 
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="zzz product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="xxx product data items" 
        <?php //if($_settingHelper->getConfig('product_detail/detail_element/use_tabs')==1): ?>
        <?php //endif; ?>
        >
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class=" carro data item title <?php echo $alias; ?>">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                </div>
                <div test-texto class="data item content" >
                    <?php /* @escapeNotVerified */ echo $html; ?>
                    <!--div class="underdetail"><p>Aqui puedo agregar mas información</p></div-->
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>

